// CARBON_FOOT_PRINT
export const SET_PERIOD = "SET_PERIOD";
export const SET_COUNTRY_BY_MARK = "SET_COUNTRY_BY_MARK";
export const SET_COUNTRY_BY_HOTEL = "SET_COUNTRY_BY_HOTEL";
export const SET_COUNTRY_BY_VEHICLE = "SET_COUNTRY_BY_VEHICLE";

// ROLES

